name: BTC feed (TAAPI bulk)

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

concurrency:
  group: btc-taapi-feed
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  push-feed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Build & push BTC feed
        id: feed
        env:
          TAAPI_SECRET: ${{ secrets.TAAPI_SECRET }}
          GIST_ID:      ${{ secrets.GIST_ID }}
          GIST_TOKEN:   ${{ secrets.GIST_TOKEN }}
        run: |
          python btc_feed.py > rawurl.txt
          echo "rawurl=$(cat rawurl.txt)" >> "$GITHUB_OUTPUT"

      - name: Print latest raw URL
        run: echo "BTC feed → ${{ steps.feed.outputs.rawurl }}"
