name: BTC feed (TAAPI bulk)

on:
  schedule:
    - cron: "*/15 * * * *"      # elke 15 min  🔄
  workflow_dispatch:             # handmatige trigger

jobs:
  push-feed:
    runs-on: ubuntu-latest

    steps:
      # 1. Repo klonen
      - uses: actions/checkout@v4            # checkout-action 📄&#8203;:contentReference[oaicite:0]{index=0}

      # 2. Python klaarzetten
      - uses: actions/setup-python@v5        # setup-python-action 📦&#8203;:contentReference[oaicite:1]{index=1}
        with:
          python-version: "3.11"

      # 3. Dependencies (alleen requests nodig)
      - name: Install Python dependency
        run: pip install --no-cache-dir requests

      # 4. Feed ophalen & Gist updaten
      - name: Update BTC TAAPI feed
        env:
          TAAPI_SECRET: ${{ secrets.TAAPI_SECRET }}   # ➜ nieuw
          GIST_ID:      ${{ secrets.GIST_ID }}
          GIST_TOKEN:   ${{ secrets.GIST_TOKEN }}
        run: python btc_feed_taapi.py
