name: KuCoin BTC feed

on:
  schedule:
    - cron: "*/15 * * * *"        # elke 15 min
  workflow_dispatch:

jobs:
  push-feed:
    runs-on: ubuntu-latest

    steps:
      # 1. Repo klonen
      - uses: actions/checkout@v4

      # 2. Python klaarzetten
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3. Dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ] && [ -s requirements.txt ]; then
            pip install --no-cache-dir -r requirements.txt
          else
            pip install --no-cache-dir pandas ta requests
          fi

      # 4. Feed genereren & Gist bijwerken
      - name: Update BTC Gist feed
        env:
          GIST_TOKEN:  ${{ secrets.GIST_TOKEN }}
          GIST_ID:     ${{ secrets.GIST_ID_BTC }}  # gebruik een aparte secret/ID
        run: python kucoin_btc_feed.py
